

set(INCLUDE_DRAW2D_CAIRO TRUE)
set(INCLUDE_DIRECT2D TRUE)
set(INCLUDE_DIRECTX11 TRUE)
set(INCLUDE_DIRECTX12 TRUE)
set(INCLUDE_OPENGL TRUE)
set(INCLUDE_VULKAN TRUE)
set(INCLUDE_IMAGING_FREEIMAGE TRUE)
set(INCLUDE_AUDIO TRUE)
set(INCLUDE_OPENGL TRUE)
set(HAS_APP_VERIWELL TRUE)
set(HAS_AUDIO_SYSTEM TRUE)
set(INCLUDE_REDSHIFT TRUE)


